import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Каталог молитв - Все православные молитвы | Молитва дня',
    description: 'Полный каталог православных молитв с удобным поиском и фильтрами. Найдите нужную молитву среди 442 молитв по категориям, тегам или быстрым пресетам. Молитвы о здравии, о детях, семейные, защитные и другие.',
    keywords: [
        'каталог молитв',
        'все молитвы',
        'православные молитвы',
        'поиск молитв',
        'молитвы о здравии',
        'молитвы о детях',
        'семейные молитвы',
        'молитвы о работе',
        'защитные молитвы',
        'благодарственные молитвы',
        'покаянные молитвы',
        'молитвы в путешествии',
        'православный молитвенник',
        'духовные практики',
        'православие',
        'духовность',
        'вера'
    ].join(', '),
    authors: [{ name: 'Молитва дня' }],
    creator: 'Молитва дня',
    publisher: 'Молитва дня',
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    metadataBase: new URL('https://molitvy365.ru'),
    alternates: {
        canonical: '/catalog',
    },
    openGraph: {
        title: 'Каталог молитв - Все православные молитвы',
        description: 'Полный каталог православных молитв с удобным поиском и фильтрами. Найдите нужную молитву среди 442 молитв.',
        type: 'website',
        locale: 'ru_RU',
        url: '/catalog',
        siteName: 'Молитва дня',
        images: [
            {
                url: '/og-image.jpg',
                width: 1200,
                height: 630,
                alt: 'Каталог молитв - Все православные молитвы',
            },
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Каталог молитв - Все православные молитвы',
        description: 'Полный каталог православных молитв с удобным поиском и фильтрами.',
        images: ['/og-image.jpg'],
    },
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
    other: {
        'language': 'ru',
        'geo.region': 'RU',
        'geo.placename': 'Россия',
        'distribution': 'global',
        'rating': 'general',
        'revisit-after': '1 days',
        'mobile-web-app-capable': 'yes',
        'apple-mobile-web-app-capable': 'yes',
        'apple-mobile-web-app-status-bar-style': 'default',
        'apple-mobile-web-app-title': 'Молитва дня',
        'HandheldFriendly': 'true',
        'MobileOptimized': '320',
        'content-type': 'text/html; charset=UTF-8',
        'content-language': 'ru',
        'audience': 'all',
        'target': 'all',
    },
};
